<?php

/**
 * @file
 * Module file for LookingGlass
 * 
 * @see hook_menu
 * 
*/

/**
 * Impliments hook_menu()
 *
*/

function test7_theme() {
    return array(
    'my_LookingGlass' => array(
      'template' => 'LookingGlass',
      'variables' => array('title' => NULL),
    ),
  );
}

function LookingGlass_menu() {
  // Menu items are defined by placing them in an $items array. The array key
  // (in this case 'LookingGlass') is the path that defines the menu router
  // entry, so the page will be accessible from the URL
  // example.com/test7.
  $items['LookingGlass'] = array(
      
     // The menu title.
     'title' => 'LookingGlass',

     // Description (hover flyover for menu link)
     'description' => 'Simple menu',
     
     'page callback' => '_LookingGlass_menu_page',
     
     'access callback' => TRUE,
 );

function _LookingGlass_ajax_page () {

// check whether command and host are set
    if (isset($_GET['cmd']) && isset($_GET['host'])) {
        // define available commands
        $cmds = array('host', 'mtr', 'mtr6', 'ping', 'ping6', 'traceroute', 'traceroute6');
        // verify command
        if (in_array($_GET['cmd'], $cmds)) {
            // include required scripts
            $required = array('LookingGlass.php', 'RateLimit.php', 'Config.php');
            foreach ($required as $val) {
                require 'LookingGlass/' . $val;
            }

            // instantiate LookingGlass & RateLimit
            $lg = new Telephone\LookingGlass();
            $limit = new Telephone\LookingGlass\RateLimit($rateLimit);

            // check IP against database
            $limit->rateLimit($rateLimit);

            // execute command
            $output = $lg->$_GET['cmd']($_GET['host']);
            if ($output) {
                exit();
            }
        }
    }
// report error
exit('Unauthorized request');
}
